- name: enable full keyboard access for all controls (i.e. tab in modal dialogs)
  command: defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

- name: set fast keyboard repeat rate
  command: "{{ item }}"
  with_items:
    - defaults write NSGlobalDomain KeyRepeat -int 2
    - defaults write NSGlobalDomain InitialKeyRepeat -int 15
