- name: disable natural scrolling
  command: defaults write NSGlobalDomain com.apple.swipescrolldirection -bool false

- name: disable trackpad gestures
  command: "defaults write com.apple.dock {{ item }} -int 0"
  with_items:
    - showLaunchpadGestureEnabled
    - showDesktopGestureEnabled
    - showMissionControlGestureEnabled

- name: set trackpad right corner as right click
  command: "{{ item }}"
  with_items:
    - defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
    - defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
    - defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
    - defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true
