- name: check if zsh was brewed
  shell: brew info zsh
  register: zsh_brewed
  ignore_errors: true

- name: get brewed zsh binary path
  stat:
    path: "{{ zsh_path }}"
  register: brewed_zsh_path
  ignore_errors: true
  when: zsh_brewed is successful

- name: replace path to zsh in /etc/shells
  become: yes
  become_user: root
  lineinfile:
    path: /etc/shells
    regexp: '.*zsh$'
    line: "{{ zsh_path }}"
  when: brewed_zsh_path.stat.exists

- name: "switch {{ user }}'s shell to zsh"
  become: yes
  become_user: root
  user:
    name: "{{ user }}"
    shell: "{{ zsh_path }}"
  when: brewed_zsh_path.stat.exists

- name: copy .zshrc
  template:
    src: "{{ role_path }}/templates/zshrc.j2"
    dest: "{{ home }}/.zshrc"
  when: brewed_zsh_path.stat.exists

- name: create .zshrc.local
  become: true
  file:
    path: "{{ home }}/.zshrc.local"
    state: touch
    owner: "{{ user }}"
  when: brewed_zsh_path.stat.exists

- include_tasks: pet.yml
