- name: copy .zshrc
  template:
    src: "{{ role_path }}/templates/zshrc.j2"
    dest: "{{ home }}/.zshrc"

- name: create .zshrc.local
  become: true
  file:
    path: "{{ home }}/.zshrc.local"
    state: touch
    owner: "{{ user }}"
