session_name: ams
start_directory: ~/Dev/ams
windows:
  - window_name: zsh
    panes:
      - sleep 1 && tmux select-window -t 1 && tmux_clear
  - window_name: rails
    layout: 6ca2,178x48,0,0{88x48,0,0,4,89x48,89,0[89x24,89,0,5,89x23,89,25,17]}
    panes:
      -
      - start_ams
      - bundle exec rails c
