session_name: uw
windows:
  - window_name: uw
    start_directory: ~/Dev/uw
    layout: main-vertical
    focus: true
    panes:
      -
      -
      -
  - window_name: gcrs
    start_directory: ~/Dev/gcrs
    layout: main-vertical
    panes:
      -
      -
      -
  - window_name: bas
    start_directory: ~/Dev/bas
    layout: main-vertical
    panes:
      -
      -
      -
