- name: check if ruby plugin installed
  shell: "asdf list | grep ruby"
  register: ruby_plugin_exists
  ignore_errors: true

- name: install ruby plugin for asdf
  shell: "asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git"
  when: ruby_plugin_exists is not successful

- name: check installed ruby version
  shell: "asdf list ruby | grep {{ ruby_version }}"
  register: ruby_version_exists
  ignore_errors: true

- name: copy .default-gems file
  copy:
    src: "{{ role_path }}/files/default-gems"
    dest: "{{ home }}/.default-gems"

- name: install ruby
  shell: "asdf install ruby {{ ruby_version }}"
  register: ruby_installed
  when: ruby_version_exists is not successful

- name: set global ruby version
  shell: "asdf global ruby {{ ruby_version }}"
  when: (ruby_version_exists is successful or ruby_installed is successful)

- name: copy .gemrc file
  copy:
    src: "{{ role_path }}/files/gemrc"
    dest: "{{ home }}/.gemrc"
  when: (ruby_version_exists is successful or ruby_installed is successful)
