- name: install python 2 provider
  pip:
    name: pynvim
    extra_args: --user

- name: install python 3 provider
  pip:
    name: pynvim
    extra_args: --user
    executable: pip3

- name: install node.js provider
  yarn:
    name: neovim
    global: yes
    state: latest
