- name: make sure "{{ config_path }}" dir exists
  file:
    path: '{{ config_path }}'
    state: directory

- name: symlink nvim directory
  file:
    src: '{{ role_path }}/files/nvim'
    dest: '{{ config_path }}/nvim'
    state: link
