- name: install python 2 plugin for neovim
  pip:
    name: neovim
    extra_args: --user

- name: install python 3 plugin for neovim
  pip:
    name: neovim
    extra_args: --user
    executable: pip3

- name: "create {{ neovim_config_path }}/autoload dir"
  file:
    path: "{{ neovim_config_path }}/autoload"
    state: directory

- name: install vim-plug
  get_url:
    url: "{{ vim_plug_repo }}"
    dest: "{{ neovim_config_path }}/autoload/plug.vim"
    force: yes

- name: install neovim plugins 
  command: nvim --headless "+silent! PlugInstall!" +qall!
