- name: "make sure '{{ neovim_config_path }}/autoload' dir exists"
  file:
    path: "{{ neovim_config_path }}/autoload"
    state: directory

- name: install vim-plug
  get_url:
    url: "{{ vim_plug_repo }}"
    dest: "{{ neovim_config_path }}/autoload/plug.vim"
    force: yes

- name: install neovim plugins 
  command: nvim --headless "+silent! PlugInstall!" +qall!

- name: "make sure '{{ coc_config_path }}/extensions' dir exists"
  file:
    path: "{{ coc_config_path }}/extensions"
    state: directory

- name: "initialize yarn in '{{ coc_config_path }}/extensions' dir"
  shell: "cd {{ coc_config_path }}/extensions && yarn init -y"

- name: install yarn libs
  yarn:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items:
    - prettier

- name: install coc extensions
  shell: "cd {{ coc_config_path }}/extensions && yarn add {{ item }}"
  with_items:
    - coc-css
    - coc-html
    - coc-json
    - coc-solargraph
    - coc-tsserver
    - coc-ultisnips
