- name: install vim-plug
  get_url:
    url: "{{ vim_plug_repo }}"
    dest: "{{ neovim_config_path }}/autoload/plug.vim"
    force: yes

- name: install neovim plugins 
  command: nvim --headless "+silent! PlugInstall!" +qall!
