- name: check if alacritty was brewed
  shell: brew info alacritty
  register: alacritty_brewed
  ignore_errors: true

- name: symlink alacritty directory
  file:
    src: '{{ role_path }}/files'
    dest: '{{ alacritty_config_path }}'
    state: link
  when: alacritty_brewed is successful
