- name: check if yarn plugin installed
  shell: "asdf list | grep yarn"
  register: yarn_plugin_exists
  ignore_errors: true

- name: install yarn plugin for asdf
  shell: "asdf plugin-add yarn"
  when: yarn_plugin_exists is not successful

- name: check installed yarn version
  shell: "asdf list yarn | grep {{ yarn_version }}"
  register: yarn_version_exists
  ignore_errors: true

- name: install yarn
  shell: "asdf install yarn {{ yarn_version }}"
  register: yarn_installed
  when: yarn_version_exists is not successful

- name: set global yarn version
  shell: "asdf global yarn {{ yarn_version }}"
  when: (yarn_version_exists is successful or yarn_installed is successful)
