- name: find garbage files
  find:
    paths: "{{ home }}"
    patterns: "^.*(bash|DS_Store).*$"
    use_regex: true
    hidden: true
    file_type: any
  register: garbage_files

- name: delete garbage files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ garbage_files.files }}"
