- name: find garbage files
  find:
    paths: '{{ home }}'
    patterns: '^.*(bash|DS_Store|oracle|vim).*$'
    use_regex: true
    hidden: true
    file_type: any
  register: garbage_files

- name: delete garbage files
  file:
    path: '{{ item.path }}'
    state: absent
  with_items: '{{ garbage_files.files }}'

- name: link .wgetrc file
  file:
    src: '{{ role_path }}/files/wgetrc'
    dest: '{{ config_path }}/.wgetrc'
    state: link
