- name: check postgres default database exists
  shell: "psql -l | grep {{ default_db_name }}"
  register: default_db_exists
  ignore_errors: true

- name: create postgres default database
  command: "createdb {{ default_db_name }}"
  when: default_db_exists|failed

- name: set alias in .zshrc.local
  blockinfile:
    path: "{{ home }}/.zshrc.local"
    marker: "# {mark} ansible managed block for PostgreSQL history file"
    content: "export PSQL_HISTORY=$HOME/.local/.psql_history"
