- name: check postgres default database exists
  shell: "psql -l | awk '{print $1}' | grep -w {{ default_db_name }}"
  register: default_db_exists
  ignore_errors: true

- name: create postgres default database
  command: "createdb {{ default_db_name }}"
  when: default_db_exists|failed
