- name: check if postgres plugin installed
  shell: asdf list | grep postgres
  register: postgres_plugin_exists
  ignore_errors: true

- name: install postgres plugin for asdf
  shell: asdf plugin-add postgres
  when: postgres_plugin_exists is not successful

- name: check installed postgres version
  shell: "asdf list postgres | grep {{ postgres_version }}"
  register: postgres_version_exists
  ignore_errors: true

- name: install postgres
  shell: "asdf install postgres {{ postgres_version }}"
  register: postgres_installed
  when: postgres_version_exists is not successful

- name: set global postgres version
  shell: "asdf global postgres {{ postgres_version }}"
  when: postgres_version_exists is successful or postgres_installed is successful

- name: reshim postgres
  shell: asdf reshim postgres
  when: postgres_version_exists is successful or postgres_installed is successful

- include_tasks: setup_db.yml
  when: postgres_version_exists is successful or postgres_installed is successful
