- name: "check if /usr/local/var/postgres-{{ postgres_version }} exists"
  stat:
    path: "/usr/local/var/postgres-{{ postgres_version }}"
  register: db_files

- name: initialize database files
  shell: "initdb /usr/local/var/postgres-{{ postgres_version }}"
  when: not db_files.stat.exists
  register: db_files_created

- name: check if postgres running
  shell: psql -c 'show data_directory'
  register: postgres_running
  ignore_errors: true

- name: stop postgres
  shell: "psql -c 'show data_directory' | sed -n 3p | xargs -I % sh -c 'pg_ctl -D % stop'"
  when:
    - db_files.stat.exists or db_files_created is successful
    - postgres_running is successful

- name: start postgres
  shell: "pg_ctl -D /usr/local/var/postgres-{{ postgres_version }} start"
  when: db_files.stat.exists or db_files_created is successful

- name: check postgres default database exists
  shell: "psql -l | awk '{print $1}' | grep -w {{ default_db_name }}"
  register: default_db_exists
  ignore_errors: true

- name: create postgres default database
  command: "createdb {{ default_db_name }}"
  when: default_db_exists is not successful
