#!/bin/sh

buildosx () {
  # Collect optional arguments
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -t|--tags)
        ANSIBLE_TAGS=$2
        shift
        ;;
      *)
        echo "Invalid option: $1"
        ;;
    esac
    shift
  done

  installHomeBrew () {
    if ! [[ $(which brew) ]]; then
      echo "\n=> Installing Homebrew\n"

      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
  }

  installAnsible () {
    echo "\n=> Installing Ansible\n"

    brew install ansible
  }

  buildAnsible () {
    echo "\n=> Building Ansible Playbooks\n"

    cd $HOME/.dots

    if [[ $ANSIBLE_TAGS ]]; then
      sh -ac ". ./.env && ansible-playbook ansible/main.yml -i ansible/inventory -v -K --tags $ANSIBLE_TAGS"
    else
      sh -ac ". ./.env && ansible-playbook ansible/main.yml -i ansible/inventory -v -K"
    fi
  }

  if ! [[ $(which ansible) ]]; then
    installAnsible
    buildAnsible
  else
    buildAnsible
  fi

  echo "\n=> Finished!\n"
}
