- name: check if elasticsearch was brewed
  shell: brew info elasticsearch-full
  register: elasticsearch_brewed
  ignore_errors: true

- name: change min jvm heap size
  become: yes
  become_user: root
  replace:
    path: /usr/local/etc/elasticsearch/jvm.options
    regexp: '^(##\s-Xms4g|-Xms.*g)$'
    replace: '-Xms{{ jvm_heap_size }}g'
  when: elasticsearch_brewed is successful

- name: change max jvm heap size
  become: yes
  become_user: root
  replace:
    path: /usr/local/etc/elasticsearch/jvm.options
    regexp: '^(##\s-Xmx4g|-Xmx.*g)$'
    replace: '-Xmx{{ jvm_heap_size }}g'
  when: elasticsearch_brewed is successful

- name: restart elasticsearch
  command: /usr/local/bin/brew services restart elastic/tap/elasticsearch-full
