# User this to check if settings have been applied before
- name: check hostname
  command: hostname
  register: hostname_is

- name: close system preferences
  command: osascript -e 'tell application "System Preferences" to quit'

- include_tasks: menu.yml
  tags: mac_os_menu
- include_tasks: dock.yml
  tags: mac_os_dock
- include_tasks: finder.yml
  tags: mac_os_finder
- include_tasks: trackpad.yml
  tags: mac_os_trackpad
- include_tasks: keyboard.yml
  tags: mac_os_keyboard
- include_tasks: misc.yml
  tags: mac_os_misc

# Make this nearly the last thing you do since it's used to check if settings have been applied before
- name: set computer name, hostname, etc
  become: yes
  command: "scutil --set {{ item }} {{ computer_name }}"
  with_items:
    - ComputerName
    - HostName
    - LocalHostName
  when: hostname_is.stdout != computer_name

- name: set NetBIOSName
  become: yes
  command: "defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server \
    NetBIOSName -string {{ computer_name }}"
  when: hostname_is.stdout != computer_name

- name: kill services
  command: "killall {{ item }}"
  with_items:
    - "-KILL SystemUIServer"
    - Dock
    - Finder
