- name: close system preferences
  command: osascript -e 'tell application "System Preferences" to quit'

- name: set computer name, hostname, etc
  become: yes
  shell: 'scutil --set {{ item }} {{ computer_name }}'
  with_items:
    - ComputerName
    - HostName
    - LocalHostName

- name: set NetBIOSName
  become: yes
  shell:
    "defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server \
    NetBIOSName -string {{ computer_name }}"

- include_tasks: menu.yml
  tags: mac_os_menu
- include_tasks: dock.yml
  tags: mac_os_dock
- include_tasks: finder.yml
  tags: mac_os_finder
- include_tasks: trackpad.yml
  tags: mac_os_trackpad
- include_tasks: keyboard.yml
  tags: mac_os_keyboard
- include_tasks: misc.yml
  tags: mac_os_misc

- name: kill services
  become: yes
  command: 'killall {{ item }}'
  with_items:
    - '-KILL SystemUIServer'
    - Dock
    - Finder
