[[snippets]]
  description = "Find all"
  command = "sudo find / -iname '*<name>*' 2>&1 | egrep -v 'Operation not permitted|Not a directory|Bad file descriptor|system loop detected'"
  output = ""

[[snippets]]
  description = "Find ports that are being used"
  command = "lsof -i :<port number>"
  output = ""

[[snippets]]
  description = "Uninstall all ruby gems"
  command = "for g in `gem list --no-versions`; do gem uninstall $g -a -x -I; done"
  output = ""

[[snippets]]
  description = "Fix ssh key file permissions"
  command = "chmod 400 ~/.ssh/id_rsa"
  output = ""
