[[snippets]]
  description = "Clear ZSH history"
  command = "rm $HISTFILE; reload!"
  output = ""

[[snippets]]
  description = "Kill all processes matching pattern"
  command = "pkill -f <pattern>"
  output = ""

[[snippets]]
  description = "Create a gzipped archive"
  command = "tar -czvf <file name>.tar.gz <file(s) to archive>"
  output = ""

[[snippets]]
  description = "Extract a gzipped archive"
  command = "tar -xzvf <archive>.tar.gz"
  output = ""

[[snippets]]
  description = "Find all files"
  command = "sudo find <location> -iname '*<name>*' 2>&1 | egrep -v 'Operation not permitted|Not a directory|Bad file descriptor|system loop detected'"
  output = ""

[[snippets]]
  description = "Find and delete files"
  command = "find <location> -iname '<name>' -print -exec rm -rf {} \\;"
  output = ""

[[snippets]]
  description = "Find ports that are being used"
  command = "lsof -i :<port number>"
  output = ""

[[snippets]]
  description = "Fix ssh key file permissions"
  command = "chmod 400 ~/.ssh/id_rsa"
  output = ""

[[snippets]]
  description = "Git rename local and remote branch"
  command = "git branch -m <new name> && git push origin :<old name> <new name> && git push origin -u <new name>"
  output = ""

[[snippets]]
  description = "Git delete local and remote branch"
  command = "git branch -D <branch name> && git push origin --delete <branch name>"
  output = ""

[[snippets]]
  description = "Open all files in vim"
  command = "find <directory> -type f -print | xargs echo | xargs -I {} sh -c 'nvim -p {}'"
  output = ""

[[snippets]]
  description = "Print terminal colors"
  command = "curl -s https://gist.githubusercontent.com/npearson72/e36bfb70f70bb908edb6f0148a43249f/raw/colortest.py | python3"
  output = ""

[[snippets]]
  description = "Rails DB migrate development"
  command = "bundle exec rake db:migrate RAILS_ENV=development"
  output = ""

[[snippets]]
  description = "Rails DB migrate test"
  command = "bundle exec rake db:migrate RAILS_ENV=test"
  output = ""

[[snippets]]
  description = "Rename multiple files"
  command = "for file in <file pattern>; do mv $file \"${file/<old chars>/<new chars>}\"; done"
  output = ""

[[snippets]]
  description = "Tail log with count"
  command = "tail -f <path to log file> | nl"
  output = ""

[[snippets]]
  description = "Uninstall all ruby gems"
  command = "for g in `gem list --no-versions`; do gem uninstall $g -a -x -I; done"
  output = ""
