- name: copy tmux.config
  file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ home }}/.config/.tmux.conf"
    state: link

- name: "make sure '{{ tmuxinator_path }}' dir exists"
  file:
    path: "{{ tmuxinator_path }}"
    state: directory

- name: link home tmuxinator configs
  file:
    src: "{{ role_path }}/files/tmuxinator/{{ item.src }}.yml"
    dest: "{{ tmuxinator_path }}/{{ item.dest }}.yml"
    state: link
  with_items:
    - { src: 'default', dest: 'default' }
    - { src: 'learning', dest: 'learning' }
    - { src: 'trs', dest: 'trs' }
  when: computer_type == 'home'

- name: link work tmuxinator configs
  file:
    src: "{{ role_path }}/files/tmuxinator/{{ item.src }}.yml"
    dest: "{{ tmuxinator_path }}/{{ item.dest }}.yml"
    state: link
  with_items:
    - { src: 'default', dest: 'default' }
    - { src: 'gcrs', dest: 'gcrs' }
    - { src: 'kipper', dest: 'kipper' }
    - { src: 'lms', dest: 'lms' }
    - { src: 'mp', dest: 'mp' }
    - { src: 'office', dest: 'office' }
  when: computer_type == 'work'
