name: gcrs
root: ~/Dev/gcrs
tmux_options: -f ~/.config/.tmux.conf

windows:
  - gcrs:
      layout: even-horizontal
      panes:
        - tmux send-keys -R && tmux clear-history
        - start_gcrs
