name: lms
root: ~/Dev/lms
tmux_options: -f ~/.config/.tmux.conf

windows:
  - nvim: nvim
  - zsh:
  - rails:
      layout: even-horizontal
      panes:
        - rails c
        - start_lms
  - processes:
      layout: even-horizontal
      panes:
        - start_sidekiq
        - bin/webpack-dev-server
