- name: install erlang plugin for asdf
  shell: "asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git"

- name: check installed erlang version
  shell: "asdf list erlang | grep {{ erlang_version }}"
  register: erlang_version_exists
  ignore_errors: true

- name: install erlang
  shell: "asdf install erlang {{ erlang_version }}"
  register: erlang_installed
  when: erlang_version_exists is not successful

- name: set global erlang version
  shell: "asdf global erlang {{ erlang_version }}"
  when: (erlang_version_exists is successful or erlang_installed is successful)
