- name: copy .pryrc
  template:
    src: "{{ role_path }}/files/pryrc"
    dest: "{{ home }}/.pryrc"

- name: copy stty
  become: yes
  become_user: root
  file:
    src: /bin/stty
    dest: /usr/local/sbin/stty
    state: link
