- name: check if nodejs plugin installed
  shell: asdf list | grep nodejs
  register: nodejs_plugin_exists
  ignore_errors: true

- name: install nodejs plugin for asdf
  shell: asdf plugin-add nodejs
  when: nodejs_plugin_exists is not successful

- name: import pgp keys
  shell: bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
  when: nodejs_plugin_exists is not successful

- name: check installed nodejs version
  shell: "asdf list nodejs | grep {{ nodejs_version }}"
  register: nodejs_version_exists
  ignore_errors: true

- name: install nodejs
  shell: "asdf install nodejs {{ nodejs_version }}"
  register: nodejs_installed
  when: nodejs_version_exists is not successful

- name: set global nodejs version
  shell: "asdf global nodejs {{ nodejs_version }}"
  when: nodejs_version_exists is successful or nodejs_installed is successful

- name: reshim nodejs
  shell: asdf reshim nodejs
  when: nodejs_version_exists is successful or nodejs_installed is successful
