- hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    computer_name: "{{ lookup('env', 'COMPUTER_NAME') }}"
    computer_type: "{{ lookup('env', 'COMPUTER_TYPE') }}"
  roles:
    - { role: pre_build, tags: pre_build }
    - { role: homebrew, tags: homebrew, become: yes, become_user: homebrew }
    - { role: kitty, tags: kitty }
    - { role: git, tags: git }
    - { role: hammerspoon, tags: hammerspoon }
    - { role: ripgrep, tags: ripgrep }
    - { role: ssh, tags: ssh }
    - { role: tmux, tags: tmux }
    - { role: zsh, tags: zsh }
    - { role: nodejs, tags: nodejs }
    - { role: yarn, tags: yarn }
    - { role: ruby, tags: ruby }
    - { role: neovim, tags: neovim }
    - { role: mac_os, tags: mac_os }
    - { role: post_build, tags: post_build }
