- hosts: localhost
  connection: local
  vars:
    user: "{{ lookup('env', 'USER') }}"
    home: "{{ lookup('env', 'HOME') }}"
    computer_name: "{{ lookup('env', 'COMPUTER_NAME') }}"
    computer_type: "{{ lookup('env', 'COMPUTER_TYPE') }}"
  roles:
    - { role: pre_build, tags: pre_build }
    - { role: homebrew, tags: homebrew }
    - { role: zsh, tags: zsh }
    - { role: git, tags: git }
    - { role: ruby, tags: ruby }
    - { role: nodejs, tags: nodejs }
    - { role: erlang, tags: erlang }
    - { role: elixir, tags: elixir }
    - { role: neovim, tags: neovim }
    - { role: misc, tags: misc }
    - { role: ssh, tags: ssh }
    - { role: tmux, tags: tmux }
    - { role: openconnect, tags: openconnect }
    - { role: postgres, tags: postgres }
    - { role: iterm2, tags: iterm2 }
    - { role: karabiner, tags: karabiner }
    - { role: mac_os, tags: mac_os }
    - { role: post_build, tags: post_build }
