# frozen_string_literal: true

work = File.readlines("#{Dir.home}/.dots/.env").any? do |line|
  line.match?(/COMPUTER_TYPE.*work/)
end

tap 'getantibody/tap'
tap 'elastic/tap'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/core'
tap 'homebrew/services'
tap 'knqyf263/pet'
cask 'adoptopenjdk8'
brew 'ansible'
brew 'coreutils'
brew 'asdf'
brew 'awscli'
brew 'bat'
brew 'cmake'
brew 'diff-so-fancy'
brew 'dockutil'
brew 'elastic/tap/elasticsearch-full', restart_service: true if work
brew 'elastic/tap/kibana-full' if work
brew 'fasd'
brew 'findutils'
brew 'fzf'
brew 'gawk'
brew 'gcc'
brew 'git'
brew 'gpg'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-which'
brew 'gzip'
brew 'htop'
brew 'imagemagick'
brew 'kubectl'
brew 'minikube'
brew 'mas'
brew 'neovim'
brew 'openconnect' if work
brew 'openssh'
brew 'redis', restart_service: true
brew 'ripgrep'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'unzip'
brew 'watchman'
brew 'wget'
brew 'zsh'
brew 'zsh-history-substring-search'
brew 'getantibody/tap/antibody'
brew 'knqyf263/pet/pet'
cask '1password'
cask 'alacritty'
cask 'authy'
cask 'docker'
cask 'dropbox'
cask 'font-hack-nerd-font'
cask 'google-chrome', args: { appdir: '/Applications' }
cask 'hammerspoon'
cask 'iina'
cask 'ngrok'
cask 'phantomjs'
cask 'postman'
cask 'rectangle'
cask 'slack'
cask 'transmission' unless work
mas 'Bear', id: '1091189122'.to_i
