require 'socket'
hostname = Socket.gethostname

tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/bundle"
tap "homebrew/services"
cask "caskroom/versions/java8" unless hostname == 'gemini'
brew "ansible"
brew "autojump"
brew "cmake"
brew "coreutils"
brew "ctags"
brew "diff-so-fancy"
brew "elasticsearch"
brew "findutils"
brew "gawk"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnutls"
brew "gzip"
brew "imagemagick"
brew "kibana" unless hostname == 'gemini'
brew "mas"
brew "neovim"
brew "node"
brew "openconnect" unless hostname == 'gemini'
brew "openssh"
brew "phantomjs"
brew "postgresql", restart_service: true
brew "python"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "tree"
brew "unrar"
brew "unzip"
brew "wget"
brew "zsh"
cask "1password"
cask "docker"
cask "dropbox"
cask "evernote"
cask "google-chrome", args: { appdir: '/Applications' }
cask "iterm2"
cask "java"
if hostname == 'gemini'
  cask "expressvpn"
  cask "transmission"
  cask "vagrant"
  cask "virtualbox"
  cask "vlc"
end
mas "Magnet", id: 441258766
