- name: specify preferences directory
  command: "defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string '{{ preferences_path }}'"

- name: tell iTerm2 to use the custom preferences in the directory
  command: defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
