- name: copy stty
  become: yes
  become_user: root
  file:
    src: /bin/stty
    dest: /usr/local/sbin/stty
    state: link

- name: make sure "{{ config_path }}" dir exists
  file:
    path: '{{ config_path }}'
    state: directory

- name: make sure "{{ cache_path }}" dir exists
  file:
    path: '{{ cache_path }}'
    state: directory
