- name: update mac os software
  become: yes
  command: softwareupdate -i -r
  register: mac_os_update

- debug:
    msg: "=====| WARNING: \
      The macOS updater found and installed updates! \
      Reboot your computer before re-running this playbook to avoid possible conflicts. \
      |====="
  when: mac_os_update is defined and mac_os_update.stderr != "No updates are available."

- name: exit if mac os was updated
  meta: end_play
  when: mac_os_update is defined and mac_os_update.stderr != "No updates are available."

- name: copy stty
  become: yes
  become_user: root
  file:
    src: /bin/stty
    dest: /usr/local/sbin/stty
    state: link

- name: "make sure '{{ home }}/.config' dir exists"
  file:
    path: "{{ home }}/.config"
    state: directory

- name: "make sure '{{ cache_path }}' dir exists"
  file:
    path: "{{ cache_path }}"
    state: directory
  register: cache_path_exists

- name: create a .zsh_history file
  file:
    path: "{{ cache_path }}/.zsh_history"
    state: touch
    mode: u=rw,g=rw,o=rw
  when: cache_path_exists is successful
