- name: make sure "{{ config_path }}" dir exists
  file:
    path: '{{ config_path }}'
    state: directory

- name: make sure "{{ cache_path }}" dir exists
  file:
    path: '{{ cache_path }}'
    state: directory
